spring.application.name=websec
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/websec
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.default-schema=public
spring.liquibase.liquibase-schema=public

spring.security.oauth2.client.registration.keycloak.client-id=websec-ui
spring.security.oauth2.client.registration.keycloak.client-secret=l5qHFCE6arS1af5GUXf0b2lQd88odTvZ2cjxJPGHSDL59aQoSJbtVyzPC3bNJPpvVif08tps8Lun4IgTPStT7A
spring.security.oauth2.client.registration.keycloak.scope[0]=openid
spring.security.oauth2.client.registration.keycloak.scope[1]=profile
spring.security.oauth2.client.registration.keycloak.scope[2]=email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8081/realms/websec

jwt.secret=a560d38f2b4f430eba2dece38f5c8c87dd019b243b93bcbe4a16d09681edb5ae
jwt.expiration-ms=86400000